version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: experiment_db
    ports:
      - "5432:5432"  
  web:
    build: .
    container_name: microservice_container
    ports:
      - "5000:5000"  
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/experiment_db
    volumes:
      - ./experiment_db.py:/app  
    command: python flask-script.py.py  


