version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb_experiment
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: experiment
      MONGO_INITDB_DATABASE: temperature-observability
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro



  my-flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flaskrestapi
    ports:
      - "5000:5000"
    depends_on:
      - mongodb






